/* rpcs3_spu_ffi.h — auto-generated by cbindgen, do not edit by hand. */

#ifndef RPCS3_SPU_FFI_H
#define RPCS3_SPU_FFI_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

/**
 * Run/step outcome surfaced to the C side.
 *
 * `code_or_channel` semantics by variant (filled by run/step):
 * - [`RustSpuOutcome::Continue`]: 0 (max steps reached, SPU still
 *   running but the run window expired)
 * - [`RustSpuOutcome::Stop`]: the 14-bit stop code (e.g. 0x101 for
 *   `SYS_SPU_THREAD_STOP_GROUP_EXIT`)
 * - [`RustSpuOutcome::StallRead`] / [`RustSpuOutcome::StallWrite`]:
 *   the channel index that stalled (29 = IN_MBOX, 28 = OUT_MBOX, 3 = SNR1, etc.)
 * - [`RustSpuOutcome::Error`]: the program counter at which the
 *   error fired (an unsupported opcode or LS-OOB read).
 * - [`RustSpuOutcome::MfcUnsupported`] (R7.1): the channel index in
 *   the MFC/DMA range 16..=25 that the runtime bridge's
 *   honest-fallback policy refused. The C++ bridge logs and drops
 *   the Rust session; no Rust state is committed back to
 *   `spu_thread`. Surfaced only when `rust_spu_set_refuse_mfc(h, 1)`
 *   was called on the handle.
 */
typedef enum {
  rust_spu_outcome_t_Continue = 0,
  rust_spu_outcome_t_Stop = 1,
  rust_spu_outcome_t_StallRead = 2,
  rust_spu_outcome_t_StallWrite = 3,
  rust_spu_outcome_t_Error = 4,
  rust_spu_outcome_t_MfcUnsupported = 5,
} rust_spu_outcome_t;

/**
 * Opaque handle. The C side sees only `*mut RustSpu`.
 */
typedef struct rust_spu_t rust_spu_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Allocate a fresh SPU executor instance. Returns null on
 * allocation failure (currently unreachable; `Box::new` panics
 * instead, which we catch and return null for).
 *
 * # Safety
 *
 * The returned pointer must be passed to [`rust_spu_drop`]
 * exactly once. Passing it to any other entry point after drop
 * is UB.
 */
rust_spu_t *rust_spu_new(void);

/**
 * Drop the executor and free its backing memory. Null pointer is a
 * no-op (matches `free(NULL)`).
 *
 * # Safety
 *
 * `h` must be a pointer previously returned by [`rust_spu_new`],
 * and not yet passed to this function.
 */
void rust_spu_drop(rust_spu_t *h);

/**
 * Copy `size` bytes from `bytes` into the executor's Local Store
 * at offset 0.
 *
 * Returns 0 on success; -1 on null handle / null bytes; -2 if
 * `size > SPU_LS_SIZE` (256 KiB).
 *
 * # Safety
 *
 * `bytes` must point to at least `size` readable bytes. `h` must
 * be a live handle.
 */
int32_t rust_spu_load_ls(rust_spu_t *h, const uint8_t *bytes, uint32_t size);

/**
 * Set GPR `reg` (0..127) to the 128-bit value in `bytes` (16 bytes,
 * SPU big-endian byte order — `bytes[0]` = preferred-slot MSB).
 *
 * Returns 0 on success; -1 on null handle / null bytes; -2 on
 * `reg >= 128`.
 *
 * # Safety
 *
 * `bytes` must point to at least 16 readable bytes.
 */
int32_t rust_spu_set_gpr(rust_spu_t *h, uint32_t reg, const uint8_t *bytes);

/**
 * Set the program counter (instruction pointer). The provided
 * `pc` is silently masked to 4-byte alignment + 256 KiB LS bounds.
 */
int32_t rust_spu_set_pc(rust_spu_t *h, uint32_t pc);

/**
 * Push `value` into the SPU's IN_MBOX (channel 29). Returns 0 on
 * success, -1 on null handle.
 */
int32_t rust_spu_push_inmbox(rust_spu_t *h, uint32_t value);

/**
 * Pop a value from the SPU's OUT_MBOX (channel 28). Writes the
 * drained value to `*out_value`. Returns 0 on success (mailbox
 * had a value), 1 if the mailbox was empty, -1 on null pointers.
 */
int32_t rust_spu_pop_outmbox(rust_spu_t *h, uint32_t *out_value);

/**
 * Send a signal to SNR `slot` (0 = SNR1, 1 = SNR2). The OR-merge
 * behavior matches Cell BE semantics: if a value is already pending,
 * `value` is OR-merged. Returns 0 on success, -2 on slot >= 2.
 */
int32_t rust_spu_signal(rust_spu_t *h, uint32_t slot, uint32_t value);

/**
 * R7.1 — toggle the SPU thread's MFC/DMA honest-fallback gate. When
 * `enabled` is non-zero, any subsequent `wrch` to ch16..=23 or `rdch`
 * from ch24/ch25 (or `rchcnt` on any of those) will short-circuit
 * BEFORE touching any per-channel state and surface
 * `rust_spu_outcome_t_MfcUnsupported` through
 * `rust_spu_run_until_event`. The C++ runtime bridge
 * (`SPURustBridge.cpp`) is the only intended caller; replay paths
 * never set this flag.
 *
 * R7.2 — the gate is RELAXED when `rust_spu_set_dma_get_callback`
 * is installed in addition. ch16-20 / ch22-23 wrch and ch24/25
 * rdch fall through to Phase C semantics, and `wrch ch21 (MFC_Cmd)`
 * invokes the callback to execute the real EA→LS DMA via RPCS3
 * `vm::` memory.
 *
 * Returns 0 on success, -1 if `h` is null.
 */
int32_t rust_spu_set_refuse_mfc(rust_spu_t *h, int32_t enabled);

/**
 * R7.2 — runtime DMA GET callback signature.
 *
 * Called from the SPU interpreter on `wrch ch21 (MFC_Cmd)` with
 * cmd=0x40 (plain GET) after the SPU has populated MFC_LSA / EAH /
 * EAL / Size / TagID via prior ch16-20 wrch's. The callback reads
 * `size` bytes from RPCS3 EA `eal` and writes them to the buffer at
 * `dst_ls_ptr` (a pointer into the Rust handle's LS at the
 * captured `mfc_lsa` offset, valid for `size` bytes).
 *
 * Returns 0 on success, non-zero to refuse (the interpreter then
 * surfaces `MfcUnsupported`, the bridge falls back honestly).
 */
typedef int32_t (*rust_spu_dma_get_cb_t)(void *user_data,
                                         uint32_t eal,
                                         uint8_t *dst_ls_ptr,
                                         uint32_t size,
                                         uint32_t tag);

/**
 * R7.2 — install (or clear) the runtime DMA GET callback. Pass
 * `func = NULL` to clear an existing callback. The (`func`,
 * `user_data`) pair must remain valid for the lifetime of the
 * handle's `rust_spu_run_until_event` calls.
 *
 * Returns 0 on success, -1 if `h` is null.
 */
int32_t rust_spu_set_dma_get_callback(rust_spu_t *h,
                                      rust_spu_dma_get_cb_t func,
                                      void *user_data);

/**
 * R8.1 — runtime DMA PUT callback signature.
 *
 * Called from the SPU interpreter on `wrch ch21 (MFC_Cmd)` with
 * cmd=0x20 (plain PUT) after the SPU has populated MFC_LSA / EAH /
 * EAL / Size / TagID via prior ch16-20 wrch's AND written the
 * source bytes into LS at `mfc_lsa` as part of prior interpreter
 * steps. The callback reads `size` bytes from `src_ls_ptr` (a
 * read-only pointer into the Rust SPU handle's LS at the captured
 * `mfc_lsa` offset, valid for `size` bytes) and writes them to
 * RPCS3 EA at `eal`.
 *
 * Returns 0 on success, non-zero to refuse (the interpreter then
 * surfaces `MfcUnsupported`, the bridge falls back honestly).
 */
typedef int32_t (*rust_spu_dma_put_cb_t)(void *user_data,
                                         uint32_t eal,
                                         const uint8_t *src_ls_ptr,
                                         uint32_t size,
                                         uint32_t tag);

/**
 * R8.1 — install (or clear) the runtime DMA PUT callback. Pass
 * `func = NULL` to clear an existing callback. The PUT callback is
 * independent of the GET callback: both can be installed
 * simultaneously, and the interpreter routes `wrch ch21 (MFC_Cmd)`
 * by cmd value (0x40 → GET callback, 0x20 → PUT callback).
 *
 * Returns 0 on success, -1 if `h` is null.
 */
int32_t rust_spu_set_dma_put_callback(rust_spu_t *h,
                                      rust_spu_dma_put_cb_t func,
                                      void *user_data);

/**
 * Run up to `max_steps` instructions. Returns the outcome that
 * caused the run to halt:
 *
 * - [`RustSpuOutcome::Continue`] (0): max_steps reached, SPU still
 *   running. `*out_code` set to 0. `*out_steps` set to `max_steps`.
 * - [`RustSpuOutcome::Stop`] (1): SPU executed a `stop` instruction.
 *   `*out_code` set to the 14-bit stop code.
 * - [`RustSpuOutcome::StallRead`] (2) / [`RustSpuOutcome::StallWrite`] (3):
 *   SPU parked on a blocking channel op. `*out_code` set to the
 *   channel index.
 * - [`RustSpuOutcome::Error`] (4): unsupported opcode / LS-OOB.
 *   `*out_code` set to the program counter at which the error fired.
 * - [`RustSpuOutcome::MfcUnsupported`] (5, R7.1): an MFC/DMA channel
 *   op (`wrch ch16-23`, `rdch ch24/25`, or `rchcnt` on any) was
 *   refused under the runtime bridge's honest-fallback policy.
 *   `*out_code` set to the refusing channel index. No Rust state
 *   was mutated; the bridge MUST drop the session and fall back to
 *   the C++ executor.
 */
rust_spu_outcome_t rust_spu_run_until_event(rust_spu_t *h,
                                            uint32_t max_steps,
                                            uint32_t *out_code,
                                            uint32_t *out_steps);

/**
 * Single-instruction step. Convenience wrapper around
 * [`rust_spu_run_until_event`] with `max_steps = 1`.
 */
rust_spu_outcome_t rust_spu_step(rust_spu_t *h, uint32_t *out_code);

/**
 * Read the current PC. Returns 0 on success, -1 on null pointers.
 */
int32_t rust_spu_get_pc(rust_spu_t *h, uint32_t *out_pc);

/**
 * Read GPR `reg` (0..127) into `bytes` (16 bytes, BE order).
 *
 * # Safety
 *
 * `bytes` must point to at least 16 writable bytes.
 */
int32_t rust_spu_get_gpr(rust_spu_t *h, uint32_t reg, uint8_t *bytes);

/**
 * Read up to `size` bytes from LS offset 0 into `bytes`.
 * `size` must be `<= 256 KiB`.
 *
 * # Safety
 *
 * `bytes` must point to at least `size` writable bytes.
 */
int32_t rust_spu_get_ls(rust_spu_t *h, uint8_t *bytes, uint32_t size);

/**
 * Read the SPU's parked PC (if any). Returns 0 on success and
 * writes the parked PC to `*out_pc`. Returns 1 if not parked
 * (out_pc unchanged). Returns -1 on null pointers.
 */
int32_t rust_spu_get_park_pc(rust_spu_t *h, uint32_t *out_pc);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RPCS3_SPU_FFI_H */
