#!/usr/bin/env python3
# gen_jpg.py — generate a small real JPEG for the cellJpgDec DECODE oracle, emit
# it as a C byte array (jpg_data.h) + a test.jpg for the Rust calibration.
# CC0 1.0 (public domain). Requires Pillow.
#
# The decoded pixels are produced by stb_image (the SAME decoder RPCS3 cellJpgDec
# links) — NOT by PIL — so the golden checksum must be computed by the Rust
# `rpcs3-stb-image` crate (see hle_jpgdec_decode calibration), not here. This
# only fixes the input JPEG bytes (deterministic: same image + quality).

from PIL import Image

WIDTH = 16
HEIGHT = 16
QUALITY = 90


def build_image():
    img = Image.new("RGB", (WIDTH, HEIGHT))
    px = img.load()
    for y in range(HEIGHT):
        for x in range(WIDTH):
            px[x, y] = (x * 16, y * 16, 128)  # deterministic gradient
    return img


def emit_c_array(data, path):
    with open(path, "w", newline="\n") as f:
        f.write("// jpg_data.h — generated by gen_jpg.py (CC0). DO NOT EDIT.\n")
        f.write(f"// {len(data)}-byte JPEG ({WIDTH}x{HEIGHT}, q{QUALITY}) for the "
                "cellJpgDec decode oracle.\n\n")
        f.write(f"static const unsigned int g_jpg_size = {len(data)};\n")
        f.write("static const unsigned char g_jpg_data[] = {\n")
        for i in range(0, len(data), 12):
            row = ", ".join(f"0x{b:02x}" for b in data[i:i + 12])
            f.write(f"    {row},\n")
        f.write("};\n")


if __name__ == "__main__":
    import io
    import os
    here = os.path.dirname(os.path.abspath(__file__))
    buf = io.BytesIO()
    build_image().save(buf, format="JPEG", quality=QUALITY)
    data = buf.getvalue()
    with open(os.path.join(here, "test.jpg"), "wb") as f:
        f.write(data)
    emit_c_array(data, os.path.join(here, "jpg_data.h"))
    print(f"# wrote test.jpg + jpg_data.h ({len(data)} bytes), {WIDTH}x{HEIGHT}")
