"""Regenerate rpcs3-lv2-syscall-table/src/lib.rs from the C++ source.

Run from repo root: python3 rust/rpcs3-lv2-syscall-table/gen.py
"""

from __future__ import annotations

import re
from pathlib import Path


def main() -> None:
    repo = Path(__file__).resolve().parents[2]
    src = repo / "rpcs3/Emu/Cell/lv2/lv2.cpp"
    text = src.read_text(encoding="utf-8")
    lines = text.splitlines()

    # Table lives between lines 142..=965 (0-indexed 141..=964) in the
    # current HEAD. The regex matchers are resilient to vertical drift
    # as long as this block still contains the table.
    table_text = "\n".join(lines[141:965])
    table_text = re.sub(r"/\*.*?\*/", "", table_text, flags=re.DOTALL)
    table_text = re.sub(r"//[^\n]*", "", table_text)

    pattern = re.compile(
        r"BIND_SYSC\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)"
        r"|NULL_FUNC\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)"
        r"|\bnull_func\b"
        r"|\buns_func\b"
    )

    entries = []
    for m in pattern.finditer(table_text):
        tok = m.group(0)
        if tok.startswith("BIND_SYSC"):
            entries.append(("Bound", m.group(1)))
        elif tok.startswith("NULL_FUNC"):
            entries.append(("NullFunc", m.group(2)))
        elif tok == "null_func":
            entries.append(("Null", None))
        elif tok == "uns_func":
            entries.append(("Unused", None))

    assert len(entries) == 1024, f"expected 1024 got {len(entries)}"

    counts = {"Bound": 0, "NullFunc": 0, "Null": 0, "Unused": 0}
    for k, _ in entries:
        counts[k] += 1

    header = (
        "//! `rpcs3-lv2-syscall-table` — frozen PS3 LV2 syscall table.\n"
        "//!\n"
        "//! Mirrors `rpcs3/Emu/Cell/lv2/lv2.cpp:141-965` (`g_ppu_syscall_table`).\n"
        "//! This table is **ABI-critical**: every game's syscalls dispatch through\n"
        "//! these 1024 slots. Any reordering breaks compatibility with every\n"
        "//! existing game and every RPCS3 savestate.\n"
        "//!\n"
        "//! Generated by `rust/rpcs3-lv2-syscall-table/gen.py`.\n\n"
        "/// A single syscall table slot.\n"
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n"
        "pub enum SyscallSlot {\n"
        "    /// `null_func` in C++ — slot exists but has no binding.\n"
        "    Null,\n"
        "    /// `uns_func` in C++ — slot is officially \"Unused\".\n"
        "    Unused,\n"
        "    /// Normal `BIND_SYSC(name)` binding with an HLE implementation.\n"
        "    Bound(&'static str),\n"
        "    /// `NULL_FUNC(name)` — symbol is named but has no HLE impl.\n"
        "    NullFunc(&'static str),\n"
        "}\n\n"
        "impl SyscallSlot {\n"
        "    /// Returns the syscall's symbolic name, or `None` if the slot\n"
        "    /// is unbound (Null or Unused).\n"
        "    #[must_use]\n"
        "    pub const fn name(&self) -> Option<&'static str> {\n"
        "        match self {\n"
        "            SyscallSlot::Null | SyscallSlot::Unused => None,\n"
        "            SyscallSlot::Bound(n) | SyscallSlot::NullFunc(n) => Some(n),\n"
        "        }\n"
        "    }\n\n"
        "    /// True if the slot has a real HLE implementation.\n"
        "    #[must_use]\n"
        "    pub const fn is_bound(&self) -> bool {\n"
        "        matches!(self, SyscallSlot::Bound(_))\n"
        "    }\n"
        "}\n\n"
        "/// Look up a slot by its 16-bit syscall id.\n"
        "#[must_use]\n"
        "pub fn lookup(id: u16) -> Option<&'static SyscallSlot> {\n"
        "    SYSCALL_TABLE.get(id as usize)\n"
        "}\n\n"
        "/// Reverse lookup: find the id of a syscall by name.\n"
        "#[must_use]\n"
        "pub fn find_by_name(name: &str) -> Option<u16> {\n"
        "    SYSCALL_TABLE.iter().enumerate().find_map(|(i, slot)| match slot.name() {\n"
        "        Some(n) if n == name => Some(i as u16),\n"
        "        _ => None,\n"
        "    })\n"
        "}\n\n"
        "pub const SYSCALL_TABLE_LEN: usize = 1024;\n\n"
    )

    slot_lines = []
    for kind, name in entries:
        if kind == "Null":
            slot_lines.append("    SyscallSlot::Null,")
        elif kind == "Unused":
            slot_lines.append("    SyscallSlot::Unused,")
        elif kind == "Bound":
            slot_lines.append(f'    SyscallSlot::Bound("{name}"),')
        elif kind == "NullFunc":
            slot_lines.append(f'    SyscallSlot::NullFunc("{name}"),')

    array_block = (
        "/// The full 1024-slot PS3 LV2 syscall table.\n"
        "pub const SYSCALL_TABLE: [SyscallSlot; 1024] = [\n"
        + "\n".join(slot_lines)
        + "\n];\n"
    )

    tests = """
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_has_exactly_1024_slots() {
        assert_eq!(SYSCALL_TABLE.len(), 1024);
        assert_eq!(SYSCALL_TABLE_LEN, 1024);
    }

    #[test]
    fn slot_zero_is_null() {
        assert_eq!(SYSCALL_TABLE[0], SyscallSlot::Null);
    }

    #[test]
    fn anchor_process_syscalls() {
        assert_eq!(SYSCALL_TABLE[1], SyscallSlot::Bound("sys_process_getpid"));
        assert_eq!(SYSCALL_TABLE[2], SyscallSlot::Bound("sys_process_wait_for_child"));
        assert_eq!(SYSCALL_TABLE[3], SyscallSlot::Bound("sys_process_exit3"));
    }

    #[test]
    fn anchor_ppu_thread_syscalls() {
        assert_eq!(SYSCALL_TABLE[41], SyscallSlot::Bound("_sys_ppu_thread_exit"));
        assert_eq!(SYSCALL_TABLE[43], SyscallSlot::Bound("sys_ppu_thread_yield"));
        assert_eq!(SYSCALL_TABLE[52], SyscallSlot::Bound("_sys_ppu_thread_create"));
        assert_eq!(SYSCALL_TABLE[53], SyscallSlot::Bound("sys_ppu_thread_start"));
    }

    #[test]
    fn anchor_timer_syscalls() {
        assert_eq!(SYSCALL_TABLE[70], SyscallSlot::Bound("sys_timer_create"));
        assert_eq!(SYSCALL_TABLE[71], SyscallSlot::Bound("sys_timer_destroy"));
    }

    #[test]
    fn anchor_process_exit_ids() {
        assert_eq!(SYSCALL_TABLE[22], SyscallSlot::Bound("_sys_process_exit"));
        assert_eq!(SYSCALL_TABLE[26], SyscallSlot::Bound("_sys_process_exit2"));
    }

    #[test]
    fn slot_type_distribution_is_stable() {
        let mut bound = 0;
        let mut null_func = 0;
        let mut null = 0;
        let mut unused = 0;
        for slot in &SYSCALL_TABLE {
            match slot {
                SyscallSlot::Bound(_) => bound += 1,
                SyscallSlot::NullFunc(_) => null_func += 1,
                SyscallSlot::Null => null += 1,
                SyscallSlot::Unused => unused += 1,
            }
        }
        assert_eq!(bound, %BOUND%, "bound count drift");
        assert_eq!(null_func, %NULL_FUNC%, "null_func count drift");
        assert_eq!(null, %NULL%, "null count drift");
        assert_eq!(unused, %UNUSED%, "unused count drift");
        assert_eq!(bound + null_func + null + unused, 1024);
    }

    #[test]
    fn lookup_by_id_valid() {
        assert_eq!(lookup(1), Some(&SyscallSlot::Bound("sys_process_getpid")));
        assert_eq!(lookup(52), Some(&SyscallSlot::Bound("_sys_ppu_thread_create")));
        assert_eq!(lookup(0), Some(&SyscallSlot::Null));
    }

    #[test]
    fn lookup_out_of_range() {
        assert_eq!(lookup(1024), None);
        assert_eq!(lookup(u16::MAX), None);
    }

    #[test]
    fn find_by_name_roundtrip() {
        assert_eq!(find_by_name("sys_process_getpid"), Some(1));
        assert_eq!(find_by_name("_sys_ppu_thread_create"), Some(52));
        assert_eq!(find_by_name("sys_timer_create"), Some(70));
        assert_eq!(find_by_name("definitely_not_a_real_syscall"), None);
    }

    #[test]
    fn slot_name_returns_expected_value() {
        assert_eq!(SyscallSlot::Bound("x").name(), Some("x"));
        assert_eq!(SyscallSlot::NullFunc("y").name(), Some("y"));
        assert_eq!(SyscallSlot::Null.name(), None);
        assert_eq!(SyscallSlot::Unused.name(), None);
    }

    #[test]
    fn is_bound_only_for_bind_sysc() {
        assert!(SyscallSlot::Bound("x").is_bound());
        assert!(!SyscallSlot::NullFunc("y").is_bound());
        assert!(!SyscallSlot::Null.is_bound());
        assert!(!SyscallSlot::Unused.is_bound());
    }

    /// Known aliases where the same syscall name appears at multiple ids.
    /// These are legitimate — PS3's Cell OS exposes some syscalls at both
    /// retail and DBG/ROOT slots (older/newer revisions live side-by-side).
    /// Any drift away from this set is a regression worth investigating.
    const KNOWN_ALIASES: &[(&str, &[u16])] = &[
        ("sys_memory_container_create",     &[324, 341]),
        ("sys_memory_container_destroy",    &[325, 342]),
        ("sys_sm_get_tzpb",                 &[384, 408]),
        ("sys_overlay_get_module_dbg_info", &[457, 458]),
        ("sys_pad_ldd_register_controller", &[570, 574]),
    ];

    #[test]
    fn known_aliases_are_stable() {
        for (name, expected_ids) in KNOWN_ALIASES {
            let found: Vec<u16> = SYSCALL_TABLE
                .iter()
                .enumerate()
                .filter_map(|(i, slot)| match slot.name() {
                    Some(n) if n == *name => Some(i as u16),
                    _ => None,
                })
                .collect();
            assert_eq!(&found, expected_ids, "alias list drift for {name:?}");
        }
    }

    #[test]
    fn no_unexpected_duplicate_names() {
        use std::collections::HashMap;
        let mut by_name: HashMap<&'static str, Vec<u16>> = HashMap::new();
        for (i, slot) in SYSCALL_TABLE.iter().enumerate() {
            if let Some(n) = slot.name() {
                by_name.entry(n).or_default().push(i as u16);
            }
        }
        let actual_dups: Vec<(&'static str, Vec<u16>)> = by_name
            .into_iter()
            .filter(|(_, v)| v.len() > 1)
            .map(|(k, mut v)| { v.sort_unstable(); (k, v) })
            .collect();

        for (name, ids) in &actual_dups {
            let expected = KNOWN_ALIASES.iter().find(|(n, _)| n == name);
            assert!(
                expected.is_some(),
                "unexpected duplicate {name:?} at {ids:?}"
            );
        }
        assert_eq!(actual_dups.len(), KNOWN_ALIASES.len());
    }
}
"""
    tests = (
        tests.replace("%BOUND%", str(counts["Bound"]))
        .replace("%NULL_FUNC%", str(counts["NullFunc"]))
        .replace("%NULL%", str(counts["Null"]))
        .replace("%UNUSED%", str(counts["Unused"]))
    )

    out = header + array_block + tests

    outdir = repo / "rust/rpcs3-lv2-syscall-table/src"
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "lib.rs").write_text(out, encoding="utf-8")
    print(f"wrote {outdir / 'lib.rs'} ({len(out)} bytes, 1024 slots, counts={counts})")


if __name__ == "__main__":
    main()
