#!/usr/bin/env python3
# gen_font.py — generate a SYNTHETIC, CC0 TrueType font for the cellFont
# glyph-metrics oracle, emit it as a C byte array (font_data.h), and print the
# golden glyph metrics that RPCS3's stb_truetype path would produce.
#
# The font is a fresh creation (no third-party font) so it is CC0-clean. Two
# glyphs ('A','B') are plain rectangles with KNOWN integer outlines, so the
# expected metrics are determined by construction:
#
#   metrics.width      = (xMax - xMin) * scale
#   metrics.height     = (yMax - yMin) * scale
#   metrics.h_bearingX = leftSideBearing * scale     (lsb == xMin here)
#   metrics.h_advance  = advanceWidth * scale
#   scale              = scale_y / (hheaAscent - hheaDescent)   (stbtt)
#
# With scale_y == (ascent - descent) the scale is exactly 1.0, so the metrics
# equal the raw font-unit integers (bit-exact f32). A fractional scale_y is also
# printed (IEEE-754 single via struct) to exercise the f32 multiply.
#
# CC0 1.0 (public domain). Requires fontTools (pip install fonttools).

import struct
from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen

UPM = 1000
ASCENT = 800
DESCENT = -200  # fheight = ascent - descent = 1000

# glyph name -> (codepoint, xMin, yMin, xMax, yMax, advance)
GLYPHS = {
    "A": (0x41, 100, 0, 500, 700, 600),
    "B": (0x42, 50, 0, 450, 800, 550),
}


def f32(x):
    """Round a Python float to IEEE-754 single precision (host f32 / Rust f32)."""
    return struct.unpack("<f", struct.pack("<f", x))[0]


def rect_glyph(x0, y0, x1, y1):
    pen = TTGlyphPen(None)
    pen.moveTo((x0, y0))
    pen.lineTo((x1, y0))
    pen.lineTo((x1, y1))
    pen.lineTo((x0, y1))
    pen.closePath()
    return pen.glyph()


def build():
    glyph_order = [".notdef"] + list(GLYPHS.keys())
    fb = FontBuilder(UPM, isTTF=True)
    fb.setupGlyphOrder(glyph_order)
    fb.setupCharacterMap({cp: name for name, (cp, *_rest) in GLYPHS.items()})

    glyphs = {".notdef": rect_glyph(0, 0, 0, 0)}
    metrics = {".notdef": (UPM, 0)}
    for name, (_cp, xmin, ymin, xmax, ymax, adv) in GLYPHS.items():
        glyphs[name] = rect_glyph(xmin, ymin, xmax, ymax)
        metrics[name] = (adv, xmin)  # (advanceWidth, leftSideBearing==xMin)

    fb.setupGlyf(glyphs)
    fb.setupHorizontalMetrics(metrics)
    fb.setupHorizontalHeader(ascent=ASCENT, descent=DESCENT)
    fb.setupNameTable({"familyName": "FreezeTest", "styleName": "Regular"})
    fb.setupOS2(sTypoAscender=ASCENT, sTypoDescender=DESCENT)
    fb.setupPost()
    return fb


def emit_c_array(data, path):
    with open(path, "w", newline="\n") as f:
        f.write("// font_data.h — generated by gen_font.py (CC0). DO NOT EDIT.\n")
        f.write(f"// Synthetic {len(data)}-byte TrueType font for the cellFont "
                "metrics oracle.\n\n")
        f.write(f"static const unsigned int g_font_size = {len(data)};\n")
        f.write("static const unsigned char g_font_data[] = {\n")
        for i in range(0, len(data), 12):
            row = ", ".join(f"0x{b:02x}" for b in data[i:i + 12])
            f.write(f"    {row},\n")
        f.write("};\n")


def golden():
    fheight = ASCENT - DESCENT
    print(f"# fheight (ascent-descent) = {fheight}")
    for name, (cp, xmin, ymin, xmax, ymax, adv) in GLYPHS.items():
        lsb = xmin
        for scale_y in (float(fheight), 32.0):
            scale = f32(f32(scale_y) / f32(fheight))
            width = f32(float(xmax - xmin) * scale)
            height = f32(float(ymax - ymin) * scale)
            hbx = f32(float(lsb) * scale)
            hadv = f32(float(adv) * scale)
            def bits(v):
                return struct.unpack("<I", struct.pack("<f", v))[0]
            print(f"'{name}' (0x{cp:02x}) scale_y={scale_y:g} scale={scale!r}")
            print(f"    width      = {width!r}   bits=0x{bits(width):08x}")
            print(f"    height     = {height!r}   bits=0x{bits(height):08x}")
            print(f"    h_bearingX = {hbx!r}   bits=0x{bits(hbx):08x}")
            print(f"    h_advance  = {hadv!r}   bits=0x{bits(hadv):08x}")


if __name__ == "__main__":
    import os
    here = os.path.dirname(os.path.abspath(__file__))
    fb = build()
    ttf_path = os.path.join(here, "testfont.ttf")
    fb.save(ttf_path)
    with open(ttf_path, "rb") as f:
        data = f.read()
    emit_c_array(data, os.path.join(here, "font_data.h"))
    print(f"# wrote {ttf_path} ({len(data)} bytes) + font_data.h")
    golden()
