#!/usr/bin/env python3
# gen_png.py — generate a small baseline RGB PNG for the cellPngDec DECODE oracle
# + emit it as a C byte array (png_data.h) + a test.png for the Rust calibration.
# CC0 1.0. Requires Pillow. Baseline (no gamma/sRGB/interlace) so stb_image and
# RPCS3's libpng spec-decode to IDENTICAL pixels.
from PIL import Image
W, H = 16, 16
def build():
    img = Image.new("RGB", (W, H))
    px = img.load()
    for y in range(H):
        for x in range(W):
            px[x, y] = (x * 16, y * 16, 64)
    return img
def emit(data, path):
    with open(path, "w", newline="\n") as f:
        f.write("// png_data.h — generated by gen_png.py (CC0). DO NOT EDIT.\n\n")
        f.write(f"static const unsigned int g_png_size = {len(data)};\n")
        f.write("static const unsigned char g_png_data[] = {\n")
        for i in range(0, len(data), 12):
            f.write("    " + ", ".join(f"0x{b:02x}" for b in data[i:i+12]) + ",\n")
        f.write("};\n")
if __name__ == "__main__":
    import io, os
    here = os.path.dirname(os.path.abspath(__file__))
    buf = io.BytesIO()
    # optimize=False, no gamma -> baseline PNG
    build().save(buf, format="PNG", optimize=False)
    data = buf.getvalue()
    open(os.path.join(here, "test.png"), "wb").write(data)
    emit(data, os.path.join(here, "png_data.h"))
    print(f"# wrote test.png + png_data.h ({len(data)} bytes), {W}x{H} RGB baseline")
