#!/usr/bin/env python3
# gen_png.py — generate a minimal, valid RGB PNG for the cellPngDec header
# oracle, emit it as a C byte array (png_data.h), and print the expected info.
# CC0 1.0 (public domain). Uses only the stdlib (zlib + struct).
#
# A solid-black RGB image: the IHDR (width/height/bit_depth/color_type) is what
# cellPngDecReadHeader reports, and a solid raster compresses to a tiny IDAT.

import struct
import zlib

WIDTH = 320
HEIGHT = 240
BIT_DEPTH = 8
COLOR_TYPE = 2  # PNG_COLOR_TYPE_RGB -> CELL_PNGDEC_RGB(2), numComponents 3

SIGNATURE = bytes([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A])


def chunk(tag, data):
    body = tag + data
    return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)


def build():
    ihdr = struct.pack(">IIBBBBB", WIDTH, HEIGHT, BIT_DEPTH, COLOR_TYPE, 0, 0, 0)
    # Solid-black raster: each row = 1 filter byte (0) + WIDTH*3 zero bytes.
    raw = bytes(HEIGHT * (1 + WIDTH * 3))
    idat = zlib.compress(raw, 9)
    return SIGNATURE + chunk(b"IHDR", ihdr) + chunk(b"IDAT", idat) + chunk(b"IEND", b"")


def emit_c_array(data, path):
    with open(path, "w", newline="\n") as f:
        f.write("// png_data.h — generated by gen_png.py (CC0). DO NOT EDIT.\n")
        f.write(f"// Minimal {len(data)}-byte RGB PNG ({WIDTH}x{HEIGHT}) for the "
                "cellPngDec header oracle.\n\n")
        f.write(f"static const unsigned int g_png_size = {len(data)};\n")
        f.write("static const unsigned char g_png_data[] = {\n")
        for i in range(0, len(data), 12):
            row = ", ".join(f"0x{b:02x}" for b in data[i:i + 12])
            f.write(f"    {row},\n")
        f.write("};\n")


if __name__ == "__main__":
    import os
    here = os.path.dirname(os.path.abspath(__file__))
    data = build()
    emit_c_array(data, os.path.join(here, "png_data.h"))
    print(f"# wrote png_data.h ({len(data)} bytes)")
    print(f"# expected: width={WIDTH} height={HEIGHT} num_comp=3 "
          f"color_space=2(RGB) bit_depth={BIT_DEPTH}")
