// single_font_metrics_v1 — cellFont byte-exact glyph metrics.
// CC0 1.0 (public domain). See LICENSE.md.
//
// The first cellFont RENDERING slice: glyph METRICS (no rasterization). RPCS3
// cellFont uses stb_truetype; the Rust port uses the faithful `stb_truetype`
// crate, so metrics are byte-exact. This homebrew embeds a synthetic CC0 font
// (font_data.h, generated by gen_font.py) and checks cellFontGetCharGlyphMetrics
// against golden bit patterns BOTH ways:
//   scale_y = 1000 (= ascent-descent) -> scale 1.0 -> metrics == font-unit ints
//   scale_y = 32                       -> fractional f32, bit-exact IEEE golden
//
// Sequence: fontInit -> fontInitLibraryFreeType -> fontOpenFontMemory ->
// fontSetScalePixel -> fontGetCharGlyphMetrics. Any failure returns a distinct
// 0xBADn; a full byte-exact match returns 0xC0DE.

#include <ppu-types.h>
#include <font/font.h>
#include <font/fontFT.h>
#include <sys/process.h>
#include <string.h>

#include "font_data.h" // g_font_data[], g_font_size (synthetic CC0 font)

SYS_PROCESS_PARAM(1001, 0x10000);

// PSL1GHT's font.h has a typo for this prototype ("fontontSetScalePixel"); the
// library symbol is the correct name. Declare it ourselves for the proper f32
// ABI (avoids an implicit-declaration that would promote the args to double).
extern s32 fontSetScalePixel(font *f, f32 w, f32 h);

static u32 g_filecache[256];

// Byte-exact compare: the raw 32-bit pattern of an f32 vs an expected value.
static int feq_bits(float v, unsigned int expected_bits)
{
    unsigned int b;
    memcpy(&b, &v, 4);
    return b == expected_bits;
}

int main(void)
{
    fontConfig config;
    fontConfig_initialize(&config);
    config.fileCache.buffer = g_filecache;
    config.fileCache.size = sizeof(g_filecache);
    if (fontInit(&config) != 0) {
        return 0xBAD0;
    }

    fontLibraryConfigFT ftcfg;
    fontLibraryConfigFT_initialize(&ftcfg);
    const fontLibrary *lib = NULL;
    if (fontInitLibraryFreeType(&ftcfg, &lib) != 0 || lib == NULL) {
        return 0xBAD1;
    }

    font f;
    if (fontOpenFontMemory(lib, (void *)g_font_data, g_font_size, 0, 0, &f) != 0) {
        return 0xBAD2;
    }

    fontGlyphMetrics m;

    // scale_y = ascent-descent = 1000 -> scale 1.0 -> exact font-unit integers.
    if (fontSetScalePixel(&f, 1000.0f, 1000.0f) != 0) {
        return 0xBAD3;
    }
    if (fontGetCharGlyphMetrics(&f, 'A', &m) != 0) {
        return 0xBAD4;
    }
    if (!feq_bits(m.width, 0x43c80000)) {
        return 0xBAD5; // 400.0
    }
    if (!feq_bits(m.height, 0x442f0000)) {
        return 0xBAD6; // 700.0
    }
    if (!feq_bits(m.horizontal.bearingX, 0x42c80000)) {
        return 0xBAD7; // 100.0
    }
    if (!feq_bits(m.horizontal.advance, 0x44160000)) {
        return 0xBAD8; // 600.0
    }

    // scale_y = 32 -> scale = 32/1000 -> fractional, bit-exact IEEE golden.
    if (fontSetScalePixel(&f, 32.0f, 32.0f) != 0) {
        return 0xBAD9;
    }
    if (fontGetCharGlyphMetrics(&f, 'A', &m) != 0) {
        return 0xBADA;
    }
    if (!feq_bits(m.width, 0x414ccccd)) {
        return 0xBADB; // 12.80000019
    }
    if (!feq_bits(m.height, 0x41b33334)) {
        return 0xBADC; // 22.40000153
    }
    if (!feq_bits(m.horizontal.bearingX, 0x404ccccd)) {
        return 0xBADD; // 3.200000048
    }
    if (!feq_bits(m.horizontal.advance, 0x4199999a)) {
        return 0xBADE; // 19.20000076
    }

    // Horizontal layout (cellFont.cpp:536) at scale_y=1000 (scale 1.0):
    // baseLineY=ascent=800, lineHeight=ascent-descent+lineGap=1000, effectHeight=lineGap=0.
    if (fontSetScalePixel(&f, 1000.0f, 1000.0f) != 0) {
        return 0xBADF;
    }
    fontHorizontalLayout hl;
    if (fontGetHorizontalLayout(&f, &hl) != 0) {
        return 0xBAE0;
    }
    if (!feq_bits(hl.baseLineY, 0x44480000)) {
        return 0xBAE1; // 800.0
    }
    if (!feq_bits(hl.lineHeight, 0x447a0000)) {
        return 0xBAE2; // 1000.0
    }
    if (!feq_bits(hl.effectHeight, 0x00000000)) {
        return 0xBAE3; // 0.0
    }

    return 0xC0DE;
}
